<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            // Alat Tulis (banyak merek dan jenis)
            [
                'name' => 'Pensil 2B Faber-Castell',
                'description' => 'Pensil 2B berkualitas dari Faber-Castell, cocok untuk ujian dan menggambar.',
                'price' => 4000,
                'stock' => 120,
                'category_id' => 1,
                'is_active' => true,
            ],
            [
                'name' => 'Pensil 2B Staedtler',
                'description' => 'Pensil 2B dari Staedtler, tahan lama dan nyaman digunakan.',
                'price' => 4500,
                'stock' => 100,
                'category_id' => 1,
                'is_active' => true,
            ],
            [
                'name' => 'Pulpen Hitam Pilot',
                'description' => 'Pulpen tinta hitam merk Pilot dengan grip nyaman dan tinta cepat kering.',
                'price' => 7000,
                'stock' => 150,
                'category_id' => 1,
                'is_active' => true,
            ],
            [
                'name' => 'Pulpen Biru Snowman',
                'description' => 'Pulpen tinta biru merk Snowman, cocok untuk menulis sehari-hari.',
                'price' => 6000,
                'stock' => 140,
                'category_id' => 1,
                'is_active' => true,
            ],
            [
                'name' => 'Penghapus Karet Staedtler',
                'description' => 'Penghapus karet berkualitas tinggi dari Staedtler, tidak meninggalkan bekas.',
                'price' => 3500,
                'stock' => 130,
                'category_id' => 1,
                'is_active' => true,
            ],
            [
                'name' => 'Penghapus Karet Faber-Castell',
                'description' => 'Penghapus karet dari Faber-Castell, lembut dan efektif menghapus.',
                'price' => 3000,
                'stock' => 110,
                'category_id' => 1,
                'is_active' => true,
            ],
            [
                'name' => 'Penggaris Plastik 30cm',
                'description' => 'Penggaris plastik transparan panjang 30cm, cocok untuk menggambar dan mengukur.',
                'price' => 7000,
                'stock' => 80,
                'category_id' => 1,
                'is_active' => true,
            ],
            [
                'name' => 'Penggaris Kayu 30cm',
                'description' => 'Penggaris kayu natural panjang 30cm, kuat dan tahan lama.',
                'price' => 9000,
                'stock' => 60,
                'category_id' => 1,
                'is_active' => true,
            ],
            [
                'name' => 'Spidol Permanent Hitam',
                'description' => 'Spidol permanent hitam untuk menulis di berbagai permukaan.',
                'price' => 12000,
                'stock' => 90,
                'category_id' => 1,
                'is_active' => true,
            ],
            [
                'name' => 'Stabilo Highlighter Warna-warni',
                'description' => 'Set stabilo highlighter dengan berbagai warna cerah untuk menandai catatan.',
                'price' => 25000,
                'stock' => 70,
                'category_id' => 1,
                'is_active' => true,
            ],
            [
                'name' => 'Penghapus Spidol Whiteboard',
                'description' => 'Penghapus khusus untuk whiteboard, mudah digunakan dan bersih.',
                'price' => 15000,
                'stock' => 50,
                'category_id' => 1,
                'is_active' => true,
            ],

            // Makanan & Minuman (lebih dari 10 item)
            [
                'name' => 'Kue Brownies Coklat',
                'description' => 'Brownies coklat lembut dan legit dengan topping keju.',
                'price' => 35000,
                'stock' => 20,
                'category_id' => 2,
                'is_active' => true,
            ],
            [
                'name' => 'Jus Buah Segar Mangga',
                'description' => 'Jus mangga segar tanpa pengawet, dikemas dalam botol 500ml.',
                'price' => 15000,
                'stock' => 30,
                'category_id' => 2,
                'is_active' => true,
            ],
            [
                'name' => 'Jus Buah Segar Jeruk',
                'description' => 'Jus jeruk segar tanpa pengawet, dikemas dalam botol 500ml.',
                'price' => 15000,
                'stock' => 30,
                'category_id' => 2,
                'is_active' => true,
            ],
            [
                'name' => 'Keripik Pisang Original',
                'description' => 'Keripik pisang renyah dengan rasa original, cemilan sehat.',
                'price' => 20000,
                'stock' => 50,
                'category_id' => 2,
                'is_active' => true,
            ],
            [
                'name' => 'Keripik Pisang Balado',
                'description' => 'Keripik pisang renyah dengan rasa pedas balado.',
                'price' => 22000,
                'stock' => 50,
                'category_id' => 2,
                'is_active' => true,
            ],
            [
                'name' => 'Roti Tawar Coklat',
                'description' => 'Roti tawar isi coklat, cocok untuk sarapan atau cemilan.',
                'price' => 12000,
                'stock' => 40,
                'category_id' => 2,
                'is_active' => true,
            ],
            [
                'name' => 'Roti Tawar Keju',
                'description' => 'Roti tawar isi keju, lembut dan gurih.',
                'price' => 12000,
                'stock' => 40,
                'category_id' => 2,
                'is_active' => true,
            ],
            [
                'name' => 'Es Teh Manis',
                'description' => 'Es teh manis segar dalam kemasan botol 500ml.',
                'price' => 10000,
                'stock' => 60,
                'category_id' => 2,
                'is_active' => true,
            ],
            [
                'name' => 'Es Jeruk Segar',
                'description' => 'Es jeruk segar dengan rasa asam manis alami.',
                'price' => 12000,
                'stock' => 50,
                'category_id' => 2,
                'is_active' => true,
            ],
            [
                'name' => 'Snack Kacang Goreng',
                'description' => 'Kacang goreng renyah dan gurih, cemilan favorit siswa.',
                'price' => 15000,
                'stock' => 70,
                'category_id' => 2,
                'is_active' => true,
            ],
            [
                'name' => 'Snack Kerupuk Udang',
                'description' => 'Kerupuk udang renyah, cocok untuk teman makan.',
                'price' => 15000,
                'stock' => 70,
                'category_id' => 2,
                'is_active' => true,
            ],

            // LKS (beberapa mata pelajaran SMK, kelas 10,11,12)
            [
                'name' => 'LKS Matematika SMK Kelas 10',
                'description' => 'Lembar Kerja Siswa Matematika untuk SMK kelas 10, lengkap dengan soal dan pembahasan.',
                'price' => 30000,
                'stock' => 40,
                'category_id' => 3,
                'is_active' => true,
            ],
            [
                'name' => 'LKS Matematika SMK Kelas 11',
                'description' => 'Lembar Kerja Siswa Matematika untuk SMK kelas 11, materi lanjutan dan soal latihan.',
                'price' => 32000,
                'stock' => 35,
                'category_id' => 3,
                'is_active' => true,
            ],
            [
                'name' => 'LKS Matematika SMK Kelas 12',
                'description' => 'Lembar Kerja Siswa Matematika untuk SMK kelas 12, persiapan ujian akhir.',
                'price' => 35000,
                'stock' => 30,
                'category_id' => 3,
                'is_active' => true,
            ],
            [
                'name' => 'LKS Bahasa Indonesia SMK Kelas 10',
                'description' => 'Lembar Kerja Siswa Bahasa Indonesia untuk SMK kelas 10.',
                'price' => 28000,
                'stock' => 40,
                'category_id' => 3,
                'is_active' => true,
            ],
            [
                'name' => 'LKS Bahasa Indonesia SMK Kelas 11',
                'description' => 'Lembar Kerja Siswa Bahasa Indonesia untuk SMK kelas 11.',
                'price' => 30000,
                'stock' => 35,
                'category_id' => 3,
                'is_active' => true,
            ],
            [
                'name' => 'LKS Bahasa Indonesia SMK Kelas 12',
                'description' => 'Lembar Kerja Siswa Bahasa Indonesia untuk SMK kelas 12.',
                'price' => 32000,
                'stock' => 30,
                'category_id' => 3,
                'is_active' => true,
            ],
            [
                'name' => 'LKS Akuntansi SMK Kelas 10',
                'description' => 'Lembar Kerja Siswa Akuntansi untuk SMK kelas 10.',
                'price' => 35000,
                'stock' => 40,
                'category_id' => 3,
                'is_active' => true,
            ],
            [
                'name' => 'LKS Akuntansi SMK Kelas 11',
                'description' => 'Lembar Kerja Siswa Akuntansi untuk SMK kelas 11.',
                'price' => 37000,
                'stock' => 35,
                'category_id' => 3,
                'is_active' => true,
            ],
            [
                'name' => 'LKS Akuntansi SMK Kelas 12',
                'description' => 'Lembar Kerja Siswa Akuntansi untuk SMK kelas 12.',
                'price' => 40000,
                'stock' => 30,
                'category_id' => 3,
                'is_active' => true,
            ],
            [
                'name' => 'LKS Teknik Komputer SMK Kelas 10',
                'description' => 'Lembar Kerja Siswa Teknik Komputer untuk SMK kelas 10.',
                'price' => 35000,
                'stock' => 40,
                'category_id' => 3,
                'is_active' => true,
            ],
            [
                'name' => 'LKS Teknik Komputer SMK Kelas 11',
                'description' => 'Lembar Kerja Siswa Teknik Komputer untuk SMK kelas 11.',
                'price' => 37000,
                'stock' => 35,
                'category_id' => 3,
                'is_active' => true,
            ],
            [
                'name' => 'LKS Teknik Komputer SMK Kelas 12',
                'description' => 'Lembar Kerja Siswa Teknik Komputer untuk SMK kelas 12.',
                'price' => 40000,
                'stock' => 30,
                'category_id' => 3,
                'is_active' => true,
            ],

            // Seragam (3 kelas: 10, 11, 12)
            [
                'name' => 'Seragam Putih Abu-abu Kelas 10',
                'description' => 'Seragam sekolah putih abu-abu lengkap untuk siswa kelas 10 SMK.',
                'price' => 150000,
                'stock' => 30,
                'category_id' => 4,
                'is_active' => true,
            ],
            [
                'name' => 'Seragam Putih Abu-abu Kelas 11',
                'description' => 'Seragam sekolah putih abu-abu lengkap untuk siswa kelas 11 SMK.',
                'price' => 155000,
                'stock' => 30,
                'category_id' => 4,
                'is_active' => true,
            ],
            [
                'name' => 'Seragam Putih Abu-abu Kelas 12',
                'description' => 'Seragam sekolah putih abu-abu lengkap untuk siswa kelas 12 SMK.',
                'price' => 160000,
                'stock' => 30,
                'category_id' => 4,
                'is_active' => true,
            ],
            [
                'name' => 'Dasi Seragam Sekolah',
                'description' => 'Dasi seragam sekolah warna merah marun, bahan nyaman dan mudah dibersihkan.',
                'price' => 25000,
                'stock' => 50,
                'category_id' => 4,
                'is_active' => true,
            ],
            [
                'name' => 'Topi Seragam Sekolah',
                'description' => 'Topi seragam sekolah dengan logo sekolah bordir, bahan katun adem.',
                'price' => 30000,
                'stock' => 40,
                'category_id' => 4,
                'is_active' => true,
            ],
            [
                'name' => 'Sepatu Sekolah Hitam',
                'description' => 'Sepatu sekolah warna hitam, bahan kulit sintetis, nyaman dipakai seharian.',
                'price' => 120000,
                'stock' => 25,
                'category_id' => 4,
                'is_active' => true,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
